### ISSUE TITLE
Additional dependency

### ISSUE THREAD

**Issue by dglava** [x-crowbar-x/PyBye#18]
In the README it says that only *python* and *python-gobject* are required, but it complains about a missing dependency (I assume it's [this one](https://pypi.org/project/python-configuration/)).
```
Traceback (most recent call last):
  File "/home/dino/Downloads/test.py", line 2, in <module>
    from configuration import *
ModuleNotFoundError: No module named 'configuration'
```

**Comment by x-crowbar-x** [comment]
Hi! It should import from the file in the folder named "configuration.py". Is the mentioned file in the same folder?

**Comment by dglava** [comment]
Sorry, my bad. I just downloaded the 1 file to test it. I didn't see there were more files.
It works as intended now.
