### ISSUE TITLE
comply to pep 0008

### ISSUE THREAD

**Issue by iaacornus** [x-crowbar-x/PyBye#19]
i think it would be beneficial if complied to pep 0008 since it would make the code more readable, i'd be willing to contribute if you agree with the proposed changes.

**Comment by x-crowbar-x** [comment]
Hello! Yeah, it won't hurt, of course. Thanks.
I tried to make it more readable, but I guess it's not enough :)

**Comment by x-crowbar-x** [comment]
I think it's good enough now..
